import { useState } from 'react'
import ScoreHeader from './ScoreHeader'
import ScannerSection from './ScannerSection'
import Recommendations from './Recommendations'

const CALENDLY_URL = 'https://calendly.com/slopsicurity/30min'

export default function SharedReport({ report, expiresInDays }) {
  const [noobify, setNoobify] = useState(false)

  if (!report) return null

  const { url, score } = report

  return (
    <div className="shared-report fade-in">

      {/* Branded header */}
      <div className="shared-header">
        <span className="shared-logo">Slopsicurity</span>
        <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
          <label className="toggle-wrap" onClick={() => setNoobify(n => !n)}>
            <span className="toggle-label">Noobify</span>
            <div className={`toggle-track ${noobify ? 'noobify-on' : ''}`}>
              <div className="toggle-thumb" />
            </div>
          </label>
          <span className="shared-badge">Security Report</span>
        </div>
      </div>

      {/* Context line */}
      <div className="shared-context">
        <span className="shared-context-url">{url}</span>
        {expiresInDays != null && (
          <span className="shared-context-expiry">
            Link expires in {expiresInDays} day{expiresInDays !== 1 ? 's' : ''}
          </span>
        )}
      </div>

      {/* Full report */}
      <ScoreHeader report={report} />

      <div className="sections">
        {report.scanners.map(scanner => (
          <ScannerSection key={scanner.name} scanner={scanner} noobify={noobify} />
        ))}
      </div>

      {report.recommendations.length > 0 && (
        <Recommendations items={report.recommendations} noobify={noobify} />
      )}

      {/* Consultation CTA */}
      <div className="shared-cta">
        <div className="shared-cta-inner">
          <div className="shared-cta-text">
            <p className="shared-cta-headline">
              Ready to fix {score.grade === 'A+' ? 'the remaining issues' : 'these issues'}?
            </p>
            <p className="shared-cta-sub">
              Book a free 30-minute consultation. We'll walk through the findings,
              prioritise what actually matters, and give you a clear action plan.
            </p>
          </div>
          <a
            className="shared-cta-btn"
            href={CALENDLY_URL}
            target="_blank"
            rel="noopener noreferrer"
          >
            Book a free consultation →
          </a>
        </div>
      </div>

      {/* Footer */}
      <p className="shared-footer">
        This report was generated by Slopsicurity — passive, non-invasive security checks.
        Not a substitute for a professional security audit.{' '}
        <a href="/" className="shared-footer-link">Run your own scan →</a>
      </p>
    </div>
  )
}
